remote_theme: pages-themes/cayman@v0.2.0
title: EarlySignal
description: EarlySignal is an innovative project focused on early detection of incorrect system and service behaviors using Machine Learning.
show_downloads: false
google_analytics: # Add your Google Analytics ID here if needed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 