remote_theme: pages-themes/cayman@v0.2.0
title: EarlySignal
show_downloads: false
google_analytics: # Add your Google Analytics ID here if needed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 